import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { BANK_ID_PATTERN } from "../../lib/questions/pack";
import { isRecord } from "../../lib/questions/validation";

export type BankEntry = {
  id: string;
  title: string;
  file: string;
  exportName?: string;
};
export const MANIFEST_PATH = "data/question-bank-manifest.json";
export const REGISTRY_PATH = "data/question-banks.generated.ts";

export function readManifest(root: string): BankEntry[] {
  const value: unknown = JSON.parse(
    readFileSync(resolve(root, MANIFEST_PATH), "utf8"),
  );
  if (!Array.isArray(value))
    throw new Error("Question bank manifest must be an array");
  const ids = new Set<string>();
  const files = new Set<string>();
  return value.map((entry: unknown) => {
    if (
      !isRecord(entry) ||
      typeof entry.id !== "string" ||
      !BANK_ID_PATTERN.test(entry.id) ||
      typeof entry.title !== "string" ||
      !entry.title.trim() ||
      typeof entry.file !== "string"
    )
      throw new Error("Invalid bank manifest entry");
    if (
      Object.keys(entry).some(
        (key) => !["id", "title", "file", "exportName"].includes(key),
      )
    )
      throw new Error(`Unknown manifest field: ${entry.id}`);
    const legacy = /^[a-z0-9-]+\.ts$/.test(entry.file);
    const pack = /^question-packs\/[a-z0-9-]+\.json$/.test(entry.file);
    if (!legacy && !pack) throw new Error(`Invalid bank file: ${entry.file}`);
    if (
      legacy &&
      (typeof entry.exportName !== "string" ||
        !/^[A-Z][A-Z0-9_]*$/.test(entry.exportName))
    )
      throw new Error(`Invalid exportName: ${entry.id}`);
    if (pack && entry.exportName !== undefined)
      throw new Error(`JSON packs have no exportName: ${entry.id}`);
    if (ids.has(entry.id) || files.has(entry.file))
      throw new Error(`Duplicate bank id or file: ${entry.id}`);
    ids.add(entry.id);
    files.add(entry.file);
    return entry as BankEntry;
  });
}

/** Explicit static imports preserve Next's single lazy bank chunk; no filesystem in the client. */
export function renderRegistry(entries: BankEntry[]): string {
  const usesPacks = entries.some((entry) => !entry.exportName);
  const lines = [
    "// Generated by npm run questions -- sync. Edit question-bank-manifest.json instead.",
    'import type { QuestionBankSource } from "@/lib/questions/catalog";',
    ...(usesPacks
      ? ['import { parseQuestionPack } from "@/lib/questions/pack";']
      : []),
    ...entries.map((entry, i) =>
      entry.exportName
        ? `import { ${entry.exportName} as bank${i} } from ${JSON.stringify(`./${entry.file.replace(/\.ts$/, "")}`)};`
        : `import bank${i} from ${JSON.stringify(`./${entry.file}`)};`,
    ),
    "",
    "export const QUESTION_BANK_SOURCES: QuestionBankSource[] = [",
    ...entries.map((entry, i) =>
      entry.exportName
        ? `  { id: ${JSON.stringify(entry.id)}, title: ${JSON.stringify(entry.title)}, questions: bank${i} },`
        : `  parseQuestionPack(bank${i}),`,
    ),
    "];",
    "",
  ];
  return lines.join("\n");
}

export function assertRegistryCurrent(
  root: string,
  entries = readManifest(root),
): void {
  if (
    readFileSync(resolve(root, REGISTRY_PATH), "utf8") !==
    renderRegistry(entries)
  )
    throw new Error(
      "Question registry is stale. Run npm run questions -- sync",
    );
}
