import type { Question } from "@/types/question";

/**
 * Listening questions transcribed from the Eduwill mock test.
 * Questions, choices, transcripts and answer key come from the book; the
 * Chinese explanations, skill tags, difficulties and vocabulary are generated.
 * Audio is synthesised — the book's own recordings are not included with it.
 * Generated by pipeline/src/pdf-import — do not hand-edit.
 */
export const IMPORTED_LISTENING_ED: Question[] = [
  {
    "id": "p2-ed-0001",
    "part": "Part 2",
    "question": "Have the company vehicles in the parking lot been cleaned?",
    "choices": {
      "A": "No, not yet.",
      "B": "I just parked it on the street.",
      "C": "I put it in the recycling bin."
    },
    "answer": "A",
    "explanation_zh": "問句為現在完成式的 yes/no 疑問句，詢問公司車輛是否已清洗。正確回答應直接回應清洗狀態，選項「No, not yet.」符合語意，表示尚未完成。",
    "skill_tag": "listening_response",
    "difficulty": "A2",
    "vocabulary": [
      "company vehicles",
      "parking lot",
      "cleaned"
    ],
    "audioScript": "Q: Have the company vehicles in the parking lot been cleaned?\n(A) No, not yet.\n(B) I just parked it on the street.\n(C) I put it in the recycling bin."
  },
  {
    "id": "p2-ed-0002",
    "part": "Part 2",
    "question": "How much will the budget increase next year?",
    "choices": {
      "A": "About 10 percent.",
      "B": "Sorry, I must have dropped it.",
      "C": "At the end of this quarter."
    },
    "answer": "A",
    "explanation_zh": "問句以 How much 開頭，詢問預算增加的金額或比例。正確回答應提供具體數字或百分比，選項「About 10 percent.」直接回應了增加幅度。",
    "skill_tag": "listening_response",
    "difficulty": "A2",
    "vocabulary": [
      "budget",
      "increase",
      "percent"
    ],
    "audioScript": "Q: How much will the budget increase next year?\n(A) About 10 percent.\n(B) Sorry, I must have dropped it.\n(C) At the end of this quarter."
  },
  {
    "id": "p2-ed-0003",
    "part": "Part 2",
    "question": "You're going to have a meeting with Mr. Woodman before you leave, aren't you?",
    "choices": {
      "A": "Yes, right after lunch.",
      "B": "I'd better take the bus.",
      "C": "Three months' parental leave."
    },
    "answer": "A",
    "explanation_zh": "問句為附加問句，確認對方是否會在離開前與 Mr. Woodman 開會。正確回答應直接回應會議時間，選項「Yes, right after lunch.」表示同意並補充具體時間。",
    "skill_tag": "listening_response",
    "difficulty": "B1",
    "vocabulary": [
      "have a meeting",
      "leave",
      "parental leave"
    ],
    "audioScript": "Q: You're going to have a meeting with Mr. Woodman before you leave, aren't you?\n(A) Yes, right after lunch.\n(B) I'd better take the bus.\n(C) Three months' parental leave."
  },
  {
    "id": "p2-ed-0004",
    "part": "Part 2",
    "question": "Aren't you going to schedule an eye doctor appointment?",
    "choices": {
      "A": "These glasses are not expensive.",
      "B": "I already scheduled one.",
      "C": "The new manager was appointed today."
    },
    "answer": "B",
    "explanation_zh": "問句為否定疑問句，詢問對方是否不打算預約眼科。正確回答應說明預約狀況，選項「I already scheduled one.」表示已預約，符合語境。",
    "skill_tag": "listening_response",
    "difficulty": "B1",
    "vocabulary": [
      "schedule",
      "appointment",
      "eye doctor"
    ],
    "audioScript": "Q: Aren't you going to schedule an eye doctor appointment?\n(A) These glasses are not expensive.\n(B) I already scheduled one.\n(C) The new manager was appointed today."
  },
  {
    "id": "p2-ed-0005",
    "part": "Part 2",
    "question": "I'm going to try to fix this copy machine.",
    "choices": {
      "A": "Double-sided copies.",
      "B": "Light fixtures for the lobby.",
      "C": "Are you sure it can be repaired?"
    },
    "answer": "C",
    "explanation_zh": "問句為陳述句，表示將嘗試修理影印機。正確回答應針對修理可行性提出疑問，選項「Are you sure it can be repaired?」直接詢問是否確定能修好，符合對話邏輯。",
    "skill_tag": "listening_response",
    "difficulty": "B1",
    "vocabulary": [
      "fix",
      "copy machine",
      "repaired"
    ],
    "audioScript": "Q: I'm going to try to fix this copy machine.\n(A) Double-sided copies.\n(B) Light fixtures for the lobby.\n(C) Are you sure it can be repaired?"
  },
  {
    "id": "p2-ed-0006",
    "part": "Part 2",
    "question": "What should we do with these brochures?",
    "choices": {
      "A": "Sure, I have time this afternoon.",
      "B": "It's close to the seashore.",
      "C": "Let me leave them at the front desk."
    },
    "answer": "C",
    "explanation_zh": "問句是「這些手冊該怎麼處理？」，屬於詢問行動建議的疑問句。選項 (C)「我把它們留在前台」直接回應了如何處理手冊，符合題意。其他選項 (A) 表示有空幫忙，但未針對處理方式；(B) 描述地點，與問題無關。",
    "skill_tag": "listening_response",
    "difficulty": "A2",
    "vocabulary": [
      "brochures",
      "front desk"
    ],
    "audioScript": "Q: What should we do with these brochures?\n(A) Sure, I have time this afternoon.\n(B) It's close to the seashore.\n(C) Let me leave them at the front desk."
  },
  {
    "id": "p2-ed-0007",
    "part": "Part 2",
    "question": "Has the policy meeting been rescheduled?",
    "choices": {
      "A": "The staffing policy.",
      "B": "Yes, it's happening next Monday instead.",
      "C": "The entire management team."
    },
    "answer": "B",
    "explanation_zh": "問句是「政策會議是否已重新安排時間？」，為 yes/no 疑問句。選項 (B)「是的，改到下週一舉行」直接肯定並提供新時間，正確回應問題。選項 (A) 提及「人事政策」，與會議時間無關；(C) 說「整個管理團隊」，也未回答問題。",
    "skill_tag": "listening_response",
    "difficulty": "B1",
    "vocabulary": [
      "policy meeting",
      "rescheduled",
      "management team"
    ],
    "audioScript": "Q: Has the policy meeting been rescheduled?\n(A) The staffing policy.\n(B) Yes, it's happening next Monday instead.\n(C) The entire management team."
  },
  {
    "id": "p2-ed-0008",
    "part": "Part 2",
    "question": "Why don't we stop by the warehouse on our way to the workshop?",
    "choices": {
      "A": "(A) The store on Oak Street.",
      "B": "(B) Sure, we have time for that.",
      "C": "(C) The topic has just changed."
    },
    "answer": "B",
    "explanation_zh": "問句是「我們何不在去研討會的路上順道去倉庫？」，為建議型疑問句，通常期待同意或拒絕。選項 (B)「當然，我們有時間這麼做」表示同意並確認可行，符合語境。選項 (A) 提到街道名稱，未回應建議；(C) 說話題改變，與問題無關。",
    "skill_tag": "listening_response",
    "difficulty": "B1",
    "vocabulary": [
      "warehouse",
      "workshop",
      "stop by"
    ],
    "audioScript": "Q: Why don't we stop by the warehouse on our way to the workshop?\n(A) (A) The store on Oak Street.\n(B) (B) Sure, we have time for that.\n(C) (C) The topic has just changed."
  },
  {
    "id": "p2-ed-0009",
    "part": "Part 2",
    "question": "Have you tried our famous salmon dish?",
    "choices": {
      "A": "(A) I'm afraid I can't make it on time.",
      "B": "(B) Yes, it was delicious.",
      "C": "(C) We need a table for six."
    },
    "answer": "B",
    "explanation_zh": "問句是「你嚐過我們有名的鮭魚料理嗎？」，為 yes/no 疑問句。選項 (B)「是的，很好吃」直接肯定並給予正面評價，正確回應。選項 (A) 表示無法準時到達，與品嚐經驗無關；(C) 要求六人桌，也不相關。",
    "skill_tag": "listening_response",
    "difficulty": "A2",
    "vocabulary": [
      "salmon dish",
      "delicious"
    ],
    "audioScript": "Q: Have you tried our famous salmon dish?\n(A) (A) I'm afraid I can't make it on time.\n(B) (B) Yes, it was delicious.\n(C) (C) We need a table for six."
  },
  {
    "id": "p2-ed-0010",
    "part": "Part 2",
    "question": "Who's the opening act at tonight's concert?",
    "choices": {
      "A": "(A) It's too crowded here.",
      "B": "(B) Sandra booked tickets.",
      "C": "(C) There're several job openings on our design team."
    },
    "answer": "B",
    "explanation_zh": "問句是「今晚音樂會的開場表演者是誰？」，詢問人物身份。選項 (B)「Sandra 訂了票」雖然未直接回答表演者，但提供了一個人名，在多益聽力中常作為間接回應；其他選項 (A) 說太擁擠，(C) 談工作職缺，均與問題無關。",
    "skill_tag": "listening_response",
    "difficulty": "B1",
    "vocabulary": [
      "opening act",
      "concert",
      "job openings"
    ],
    "audioScript": "Q: Who's the opening act at tonight's concert?\n(A) (A) It's too crowded here.\n(B) (B) Sandra booked tickets.\n(C) (C) There're several job openings on our design team."
  },
  {
    "id": "p2-ed-0011",
    "part": "Part 2",
    "question": "When do the software demonstrations start?",
    "choices": {
      "A": "(A) The schedule was e-mailed to everyone.",
      "B": "(B) A lot of attractive features.",
      "C": "(C) In the conference room, I think."
    },
    "answer": "A",
    "explanation_zh": "問句是「軟體示範何時開始？」，詢問時間。選項 (A)「時間表已用電子郵件寄給大家」間接提供了獲取時間資訊的方式，符合多益聽力常見的間接回應模式。選項 (B) 說「很多吸引人的功能」，與時間無關；(C) 回答地點「在會議室」，也不正確。",
    "skill_tag": "listening_response",
    "difficulty": "B1",
    "vocabulary": [
      "software demonstrations",
      "schedule",
      "e-mailed"
    ],
    "audioScript": "Q: When do the software demonstrations start?\n(A) (A) The schedule was e-mailed to everyone.\n(B) (B) A lot of attractive features.\n(C) (C) In the conference room, I think."
  },
  {
    "id": "p2-ed-0012",
    "part": "Part 2",
    "question": "The health inspector will be visiting the restaurant soon.",
    "choices": {
      "A": "(A) Take this to table three.",
      "B": "(B) I'm fine, thanks for asking.",
      "C": "(C) We're all set."
    },
    "answer": "C",
    "explanation_zh": "問句是陳述句「衛生檢查員很快就會來餐廳」，正確回應應表示準備好了。選項 (C) We're all set 意為「我們都準備好了」，是對即將到來的檢查最直接且合理的回應。",
    "skill_tag": "listening_response",
    "difficulty": "A2",
    "vocabulary": [
      "health inspector",
      "restaurant"
    ],
    "audioScript": "Q: The health inspector will be visiting the restaurant soon.\n(A) (A) Take this to table three.\n(B) (B) I'm fine, thanks for asking.\n(C) (C) We're all set."
  },
  {
    "id": "p2-ed-0013",
    "part": "Part 2",
    "question": "Did you find a good welding specialist?",
    "choices": {
      "A": "(A) I have some wedding invitation templates.",
      "B": "(B) Yes, he starts next week.",
      "C": "(C) The list of special guests."
    },
    "answer": "B",
    "explanation_zh": "問句是過去式一般疑問句「你找到好的焊接專家了嗎？」，正確回應應回答是否找到。選項 (B) Yes, he starts next week 先肯定找到，再補充開始工作的時間，完全符合問句要求。",
    "skill_tag": "listening_response",
    "difficulty": "B1",
    "vocabulary": [
      "welding specialist",
      "start"
    ],
    "audioScript": "Q: Did you find a good welding specialist?\n(A) (A) I have some wedding invitation templates.\n(B) (B) Yes, he starts next week.\n(C) (C) The list of special guests."
  },
  {
    "id": "p2-ed-0014",
    "part": "Part 2",
    "question": "How was the tile pattern for the restroom chosen?",
    "choices": {
      "A": "(A) The service was good.",
      "B": "(B) I like this checkered shirt.",
      "C": "(C) I wasn't involved."
    },
    "answer": "C",
    "explanation_zh": "問句以 How 開頭詢問「洗手間的磁磚圖案是如何選擇的？」，正確回應應說明選擇過程或相關情況。選項 (C) I wasn't involved 表示「我沒有參與」，是對選擇過程的合理說明。",
    "skill_tag": "listening_response",
    "difficulty": "B1",
    "vocabulary": [
      "tile pattern",
      "restroom",
      "involved"
    ],
    "audioScript": "Q: How was the tile pattern for the restroom chosen?\n(A) (A) The service was good.\n(B) (B) I like this checkered shirt.\n(C) (C) I wasn't involved."
  },
  {
    "id": "p2-ed-0015",
    "part": "Part 2",
    "question": "When are we ordering office supplies for new employees?",
    "choices": {
      "A": "(A) In front of the storage closet.",
      "B": "(B) Next week on Tuesday.",
      "C": "(C) They're training now."
    },
    "answer": "B",
    "explanation_zh": "問句以 When 開頭詢問「我們何時為新員工訂購辦公用品？」，正確回應必須提供時間。選項 (B) Next week on Tuesday 明確給出時間，符合問句要求。",
    "skill_tag": "listening_response",
    "difficulty": "A2",
    "vocabulary": [
      "office supplies",
      "new employees"
    ],
    "audioScript": "Q: When are we ordering office supplies for new employees?\n(A) (A) In front of the storage closet.\n(B) (B) Next week on Tuesday.\n(C) (C) They're training now."
  },
  {
    "id": "p2-ed-0016",
    "part": "Part 2",
    "question": "The garden lights are going to be solar-powered, right?",
    "choices": {
      "A": "We are still in the planning stages.",
      "B": "Yes, this plant grows best in the shade.",
      "C": "$250 per year."
    },
    "answer": "A",
    "explanation_zh": "問句是附加問句「花園燈將是太陽能供電的，對吧？」，正確回應應確認或說明現狀。選項 (A) We are still in the planning stages 表示「我們仍在規劃階段」，委婉說明尚未確定，是合理的回應。",
    "skill_tag": "listening_response",
    "difficulty": "B1",
    "vocabulary": [
      "solar-powered",
      "planning stages"
    ],
    "audioScript": "Q: The garden lights are going to be solar-powered, right?\n(A) We are still in the planning stages.\n(B) Yes, this plant grows best in the shade.\n(C) $250 per year."
  },
  {
    "id": "p2-ed-0017",
    "part": "Part 2",
    "question": "Where can I buy a charger for this camera?",
    "choices": {
      "A": "This has excellent resolution.",
      "B": "I can order one for you.",
      "C": "Around 2:30."
    },
    "answer": "B",
    "explanation_zh": "問句以 Where 開頭詢問「我在哪裡可以買到這台相機的充電器？」，正確回應應指出購買地點或方式。選項 (B) I can order one for you 表示「我可以幫你訂一個」，提供了替代解決方案，符合對話邏輯。",
    "skill_tag": "listening_response",
    "difficulty": "A2",
    "vocabulary": [
      "charger",
      "camera",
      "order"
    ],
    "audioScript": "Q: Where can I buy a charger for this camera?\n(A) This has excellent resolution.\n(B) I can order one for you.\n(C) Around 2:30."
  },
  {
    "id": "p2-ed-0018",
    "part": "Part 2",
    "question": "Do I need to reserve a conference room?",
    "choices": {
      "A": "Yes, Jeff will show you how.",
      "B": "I booked the trip already.",
      "C": "There's room for improvement."
    },
    "answer": "A",
    "explanation_zh": "問句是「我需要預訂會議室嗎？」，這是一般疑問句，回答需針對是否需要預訂。選項 (A) Yes, Jeff will show you how. 直接肯定回答並提供協助，符合題意。選項 (B) 提到預訂旅程，與會議室無關；選項 (C) 說「還有改進空間」，是雙關語，但未回應問題。",
    "skill_tag": "listening_response",
    "difficulty": "A2",
    "vocabulary": [
      "reserve",
      "conference room",
      "show you how"
    ],
    "audioScript": "Q: Do I need to reserve a conference room?\n(A) Yes, Jeff will show you how.\n(B) I booked the trip already.\n(C) There's room for improvement."
  },
  {
    "id": "p2-ed-0019",
    "part": "Part 2",
    "question": "When's the new department director supposed to start?",
    "choices": {
      "A": "Yes, for a summer vacation.",
      "B": "Mr. Anderson is not retiring until May.",
      "C": "No, he should be in the office."
    },
    "answer": "B",
    "explanation_zh": "問句是「新部門主管何時開始上班？」，以 When 開頭詢問時間。選項 (B) Mr. Anderson is not retiring until May. 間接回答了開始時間（五月後），因為新主管接替退休的 Anderson。選項 (A) 回答「是，為了暑假」與時間不符；選項 (C) 回答「不，他應該在辦公室」未提供時間。",
    "skill_tag": "listening_response",
    "difficulty": "B1",
    "vocabulary": [
      "department director",
      "supposed to",
      "retire"
    ],
    "audioScript": "Q: When's the new department director supposed to start?\n(A) Yes, for a summer vacation.\n(B) Mr. Anderson is not retiring until May.\n(C) No, he should be in the office."
  },
  {
    "id": "p2-ed-0020",
    "part": "Part 2",
    "question": "Should I finish designing these fliers now, or can it wait until tomorrow?",
    "choices": {
      "A": "I'm flying to San Francisco.",
      "B": "In the waiting room.",
      "C": "Tomorrow's fine."
    },
    "answer": "C",
    "explanation_zh": "問句是「我應該現在完成設計這些傳單，還是可以等到明天？」，提供兩個選項。選項 (C) Tomorrow's fine. 直接選擇「等到明天」，符合問句的第二個選項。選項 (A) 說「我要飛往舊金山」，與問題無關；選項 (B) 說「在等候室」，也不相關。",
    "skill_tag": "listening_response",
    "difficulty": "A2",
    "vocabulary": [
      "finish designing",
      "fliers",
      "wait until"
    ],
    "audioScript": "Q: Should I finish designing these fliers now, or can it wait until tomorrow?\n(A) I'm flying to San Francisco.\n(B) In the waiting room.\n(C) Tomorrow's fine."
  },
  {
    "id": "p2-ed-0021",
    "part": "Part 2",
    "question": "This laptop is becoming quite slow.",
    "choices": {
      "A": "Attendance was low.",
      "B": "When did you last check for viruses?",
      "C": "No, you shouldn't have to wait long."
    },
    "answer": "B",
    "explanation_zh": "問句是「這台筆電變得很慢了」，這是一個陳述句，暗示問題需要解決。選項 (B) When did you last check for viruses? 提出合理建議（檢查病毒），是對問題的適當回應。選項 (A) 說「出席率低」，與筆電無關；選項 (C) 說「不，你不該等太久」，未針對問題。",
    "skill_tag": "listening_response",
    "difficulty": "B1",
    "vocabulary": [
      "laptop",
      "slow",
      "check for viruses"
    ],
    "audioScript": "Q: This laptop is becoming quite slow.\n(A) Attendance was low.\n(B) When did you last check for viruses?\n(C) No, you shouldn't have to wait long."
  },
  {
    "id": "p2-ed-0022",
    "part": "Part 2",
    "question": "How much will the repairs cost?",
    "choices": {
      "A": "In about three days.",
      "B": "I'd like you to do this in pairs.",
      "C": "Everything is covered under the warranty plan."
    },
    "answer": "C",
    "explanation_zh": "問句是「修理費用是多少？」，以 How much 詢問金額。選項 (C) Everything is covered under the warranty plan. 表示所有費用由保固計畫負擔，間接回答費用為零或已包含。選項 (A) 回答「大約三天」，是時間而非金額；選項 (B) 說「我希望你們兩人一組做」，與問題無關。",
    "skill_tag": "listening_response",
    "difficulty": "B1",
    "vocabulary": [
      "repairs",
      "cost",
      "warranty plan"
    ],
    "audioScript": "Q: How much will the repairs cost?\n(A) In about three days.\n(B) I'd like you to do this in pairs.\n(C) Everything is covered under the warranty plan."
  },
  {
    "id": "p2-ed-0023",
    "part": "Part 2",
    "question": "Why don't you check the prices at a different hardware store?",
    "choices": {
      "A": "Do you know of a good one?",
      "B": "She's a software engineer.",
      "C": "You can check in after 10 o'clock."
    },
    "answer": "A",
    "explanation_zh": "問句是「你為什麼不去另一家五金店看看價格？」，這是一個建議句，以 Why don't you 開頭。選項 (A) Do you know of a good one? 反問對方是否知道好的店家，是對建議的自然回應。選項 (B) 說「她是軟體工程師」，與五金店無關；選項 (C) 說「你可以在10點後辦理入住」，也不相關。",
    "skill_tag": "listening_response",
    "difficulty": "B1",
    "vocabulary": [
      "check the prices",
      "hardware store",
      "know of"
    ],
    "audioScript": "Q: Why don't you check the prices at a different hardware store?\n(A) Do you know of a good one?\n(B) She's a software engineer.\n(C) You can check in after 10 o'clock."
  },
  {
    "id": "p2-ed-0024",
    "part": "Part 2",
    "question": "Can you give me a tour of the property on Abbey Street this afternoon?",
    "choices": {
      "A": "It has a large backyard.",
      "B": "Sorry, I won't have time until Friday.",
      "C": "Over 20 people."
    },
    "answer": "B",
    "explanation_zh": "問句是請求當天下午帶看房產，屬於對時間安排的回應。選項「Sorry, I won't have time until Friday」直接表示無法配合，是合理的拒絕答覆。其他選項「It has a large backyard」描述房產特徵，與請求無關；「Over 20 people」則答非所問。",
    "skill_tag": "listening_response",
    "difficulty": "A2",
    "vocabulary": [
      "tour",
      "property",
      "backyard"
    ],
    "audioScript": "Q: Can you give me a tour of the property on Abbey Street this afternoon?\n(A) It has a large backyard.\n(B) Sorry, I won't have time until Friday.\n(C) Over 20 people."
  },
  {
    "id": "p2-ed-0025",
    "part": "Part 2",
    "question": "Who's scheduled to do the product demonstration tomorrow?",
    "choices": {
      "A": "We're waiting for confirmation.",
      "B": "At the Wilson Hotel.",
      "C": "Let me show you a few more."
    },
    "answer": "A",
    "explanation_zh": "問句詢問明天誰負責產品示範，屬於對人選的提問。選項「We're waiting for confirmation」表示尚未確定人選，符合語境。其他選項「At the Wilson Hotel」回答地點，與問題不符；「Let me show you a few more」則是提議，非直接回應。",
    "skill_tag": "listening_response",
    "difficulty": "B1",
    "vocabulary": [
      "scheduled",
      "product demonstration",
      "confirmation"
    ],
    "audioScript": "Q: Who's scheduled to do the product demonstration tomorrow?\n(A) We're waiting for confirmation.\n(B) At the Wilson Hotel.\n(C) Let me show you a few more."
  },
  {
    "id": "p3-ed-0001",
    "part": "Part 3",
    "question": "Where most likely are the speakers?",
    "choices": {
      "A": "At a shipping company",
      "B": "At a national park",
      "C": "At a hardware store",
      "D": "At a cleaning service"
    },
    "answer": "C",
    "explanation_zh": "對話中提及「power tools（電動工具）」、「paint section（油漆區）」以及「paint-mixing machine（油漆調色機）」，這些都是五金行或建材行常見的商品與區域，因此最可能的地點是五金行。",
    "skill_tag": "listening_inference",
    "difficulty": "B1",
    "vocabulary": [
      "power tools",
      "paint section",
      "hardware store"
    ],
    "transcript": "W: Hassan, I've finished restocking the power tools. Ted said that you wanted to talk to me about an issue we're having in the paint section.\nM: That's right. The paint-mixing machine has broken down. So, we can't mix any custom paints for customers at the moment.\nW: Hmm... I wonder if it's something easy to fix.\nM: I'll take a look at the user manual to see if I can figure out the problem.",
    "question_order": 1
  },
  {
    "id": "p3-ed-0002",
    "part": "Part 3",
    "question": "According to the man, what has caused a problem?",
    "choices": {
      "A": "A staff shortage",
      "B": "A scheduling conflict",
      "C": "Some poor reviews",
      "D": "Some broken equipment"
    },
    "answer": "D",
    "explanation_zh": "男士明確說「The paint-mixing machine has broken down（油漆調色機故障了）」，因此問題是設備損壞，對應選項「Some broken equipment」。",
    "skill_tag": "listening_detail",
    "difficulty": "A2",
    "vocabulary": [
      "broken down",
      "equipment",
      "paint-mixing machine"
    ],
    "transcript": "W: Hassan, I've finished restocking the power tools. Ted said that you wanted to talk to me about an issue we're having in the paint section.\nM: That's right. The paint-mixing machine has broken down. So, we can't mix any custom paints for customers at the moment.\nW: Hmm... I wonder if it's something easy to fix.\nM: I'll take a look at the user manual to see if I can figure out the problem.",
    "question_order": 2
  },
  {
    "id": "p3-ed-0003",
    "part": "Part 3",
    "question": "What does the woman say she will do?",
    "choices": {
      "A": "Print a document",
      "B": "Hire a specialist",
      "C": "Check a manual",
      "D": "Process a payment"
    },
    "answer": "C",
    "explanation_zh": "男士說「I'll take a look at the user manual（我會查看使用手冊）」，因此他將要檢查手冊，對應選項「Check a manual」。注意題目問的是男士而非女士，但對話中男士說了這句話。",
    "skill_tag": "listening_detail",
    "difficulty": "A2",
    "vocabulary": [
      "user manual",
      "take a look at",
      "figure out"
    ],
    "transcript": "W: Hassan, I've finished restocking the power tools. Ted said that you wanted to talk to me about an issue we're having in the paint section.\nM: That's right. The paint-mixing machine has broken down. So, we can't mix any custom paints for customers at the moment.\nW: Hmm... I wonder if it's something easy to fix.\nM: I'll take a look at the user manual to see if I can figure out the problem.",
    "question_order": 3
  },
  {
    "id": "p3-ed-0004",
    "part": "Part 3",
    "question": "Who most likely is the man?",
    "choices": {
      "A": "A building owner",
      "B": "An art instructor",
      "C": "An interior designer",
      "D": "A journalist"
    },
    "answer": "C",
    "explanation_zh": "對話中男人提到他為 Osborne 女士的客廳做設計，並說她對那個房間有明確的願景，他試圖遵循。這顯示他的職業是室內設計師。",
    "skill_tag": "listening_inference",
    "difficulty": "B1",
    "vocabulary": [
      "design",
      "vision",
      "interior designer"
    ],
    "transcript": "W: I've reviewed your design for Ms. Osborne's living room, and I think you've done a great job. I love the unique style!\nM: Thank you. She had a clear vision for that room, so I tried to follow it.\nW: There's just one adjustment needed, though.\n We can't use the wood panels you selected because they've been discontinued by the manufacturer.\nM: I hadn't realized that. They're a major feature of my design.\nW: Well, you might be able to achieve the same look with wallpaper. Check out the photos of the room that Yuki did for Mr. Harris. Then you can see what I mean.",
    "question_order": 1
  },
  {
    "id": "p3-ed-0005",
    "part": "Part 3",
    "question": "What is the woman concerned about?",
    "choices": {
      "A": "Increased costs",
      "B": "Safety issues",
      "C": "Unavailable materials",
      "D": "A missed deadline"
    },
    "answer": "C",
    "explanation_zh": "女人說無法使用男人選的木質鑲板，因為製造商已停產該產品。這表示她擔心的是材料無法取得。",
    "skill_tag": "listening_detail",
    "difficulty": "B1",
    "vocabulary": [
      "discontinued",
      "manufacturer",
      "wood panels"
    ],
    "transcript": "W: I've reviewed your design for Ms. Osborne's living room, and I think you've done a great job. I love the unique style!\nM: Thank you. She had a clear vision for that room, so I tried to follow it.\nW: There's just one adjustment needed, though.\n We can't use the wood panels you selected because they've been discontinued by the manufacturer.\nM: I hadn't realized that. They're a major feature of my design.\nW: Well, you might be able to achieve the same look with wallpaper. Check out the photos of the room that Yuki did for Mr. Harris. Then you can see what I mean.",
    "question_order": 2
  },
  {
    "id": "p3-ed-0006",
    "part": "Part 3",
    "question": "What does the woman suggest doing?",
    "choices": {
      "A": "Taking a training session",
      "B": "Looking at some images",
      "C": "Contacting a manufacturer",
      "D": "Placing a rush order"
    },
    "answer": "B",
    "explanation_zh": "女人建議男人查看 Yuki 為 Harris 先生設計的房間照片，來了解用壁紙達到類似效果的意思。這是在建議他看一些圖片。",
    "skill_tag": "listening_detail",
    "difficulty": "B1",
    "vocabulary": [
      "wallpaper",
      "photos",
      "achieve the same look"
    ],
    "transcript": "W: I've reviewed your design for Ms. Osborne's living room, and I think you've done a great job. I love the unique style!\nM: Thank you. She had a clear vision for that room, so I tried to follow it.\nW: There's just one adjustment needed, though.\n We can't use the wood panels you selected because they've been discontinued by the manufacturer.\nM: I hadn't realized that. They're a major feature of my design.\nW: Well, you might be able to achieve the same look with wallpaper. Check out the photos of the room that Yuki did for Mr. Harris. Then you can see what I mean.",
    "question_order": 3
  },
  {
    "id": "p3-ed-0007",
    "part": "Part 3",
    "question": "Who are the men meeting with?",
    "choices": {
      "A": "A real estate agent",
      "B": "A mechanic",
      "C": "A safety inspector",
      "D": "An accountant"
    },
    "answer": "A",
    "explanation_zh": "對話中男性提到「the real estate agent said that it is in an excellent location」以及隨後向女性打招呼「Hi, Cindy」，可知他們正在與房地產經紀人會面。因此正確答案為 (A) A real estate agent。",
    "skill_tag": "listening_detail",
    "difficulty": "A2",
    "vocabulary": [
      "real estate agent",
      "dealership",
      "location"
    ],
    "transcript": "M1: I'm glad we were both able to visit this site in person.\nM2: Me, too. I hope it'll be suitable for our car dealership.\nM1: Well, the real estate agent said that it is in an excellent location. Oh, here she is now. Hi, Cindy.\nW: Good morning. So, what's your first impression?\nM2: It's a great neighborhood. But we need a lot of space to display our vehicles. I'm worried about the small size.\nM1: Right. We'll need extra room for customer parking as well.\nW: You know, there's a grassy area on the east side that could be paved. Let me show you the property line on the map.",
    "question_order": 1
  },
  {
    "id": "p3-ed-0008",
    "part": "Part 3",
    "question": "What are the men concerned about?",
    "choices": {
      "A": "A location is difficult to find.",
      "B": "A site is not large enough.",
      "C": "A form is missing information.",
      "D": "A parking fee is too high."
    },
    "answer": "B",
    "explanation_zh": "第二位男性說「I'm worried about the small size」，第一位男性也補充「We'll need extra room for customer parking」，顯示他們擔心場地不夠大。因此正確答案為 (B) A site is not large enough。",
    "skill_tag": "listening_detail",
    "difficulty": "A2",
    "vocabulary": [
      "display",
      "vehicles",
      "customer parking"
    ],
    "transcript": "M1: I'm glad we were both able to visit this site in person.\nM2: Me, too. I hope it'll be suitable for our car dealership.\nM1: Well, the real estate agent said that it is in an excellent location. Oh, here she is now. Hi, Cindy.\nW: Good morning. So, what's your first impression?\nM2: It's a great neighborhood. But we need a lot of space to display our vehicles. I'm worried about the small size.\nM1: Right. We'll need extra room for customer parking as well.\nW: You know, there's a grassy area on the east side that could be paved. Let me show you the property line on the map.",
    "question_order": 2
  },
  {
    "id": "p3-ed-0009",
    "part": "Part 3",
    "question": "What will the speakers most likely do next?",
    "choices": {
      "A": "Enter a building",
      "B": "View a document",
      "C": "Go to another site",
      "D": "Take some measurements"
    },
    "answer": "B",
    "explanation_zh": "女性說「Let me show you the property line on the map」，暗示她接下來會展示地圖或文件給他們看。因此正確答案為 (B) View a document。",
    "skill_tag": "listening_next_action",
    "difficulty": "B1",
    "vocabulary": [
      "property line",
      "map",
      "paved"
    ],
    "transcript": "M1: I'm glad we were both able to visit this site in person.\nM2: Me, too. I hope it'll be suitable for our car dealership.\nM1: Well, the real estate agent said that it is in an excellent location. Oh, here she is now. Hi, Cindy.\nW: Good morning. So, what's your first impression?\nM2: It's a great neighborhood. But we need a lot of space to display our vehicles. I'm worried about the small size.\nM1: Right. We'll need extra room for customer parking as well.\nW: You know, there's a grassy area on the east side that could be paved. Let me show you the property line on the map.",
    "question_order": 3
  },
  {
    "id": "p3-ed-0010",
    "part": "Part 3",
    "question": "Why is the woman calling?",
    "choices": {
      "A": "To request a discount",
      "B": "To reschedule a delivery",
      "C": "To make a payment",
      "D": "To inquire about returns"
    },
    "answer": "B",
    "explanation_zh": "女士開頭說原本今天要送貨，但詢問能否改為明天送達，因為道路施工無法進入入口。因此她打電話的目的是要重新安排送貨時間。",
    "skill_tag": "listening_main_idea",
    "difficulty": "A2",
    "vocabulary": [
      "delivery",
      "reschedule",
      "emergency repairs"
    ],
    "transcript": "W: Good morning. This is Pamela at Lubbock Sales. You were supposed to deliver some boxes today, but I'm wondering if you can do it tomorrow instead. They're carrying out emergency repairs on our road, so it's difficult to access our entrance.\nM: Don't you need the items urgently?\nW: We can wait another day. They're containers for moving our office items, and we aren't quite ready to start packing anyway.\nM: I see. Then, let me call our driver, Milton, to see if he can do it.",
    "question_order": 1
  },
  {
    "id": "p3-ed-0011",
    "part": "Part 3",
    "question": "Why did the woman order some items?",
    "choices": {
      "A": "She plans to transport some items.",
      "B": "She must repair some machinery.",
      "C": "She will give gifts to employees.",
      "D": "She is redecorating her office."
    },
    "answer": "A",
    "explanation_zh": "女士提到這些箱子是用來搬運辦公室物品的容器，而且他們還沒準備好開始打包。因此她訂購這些物品是為了運送物品。",
    "skill_tag": "listening_detail",
    "difficulty": "B1",
    "vocabulary": [
      "containers",
      "moving",
      "packing"
    ],
    "transcript": "W: Good morning. This is Pamela at Lubbock Sales. You were supposed to deliver some boxes today, but I'm wondering if you can do it tomorrow instead. They're carrying out emergency repairs on our road, so it's difficult to access our entrance.\nM: Don't you need the items urgently?\nW: We can wait another day. They're containers for moving our office items, and we aren't quite ready to start packing anyway.\nM: I see. Then, let me call our driver, Milton, to see if he can do it.",
    "question_order": 2
  },
  {
    "id": "p3-ed-0012",
    "part": "Part 3",
    "question": "What will the man do next?",
    "choices": {
      "A": "Drive to the woman's business",
      "B": "Update a company website",
      "C": "Speak to the woman's manager",
      "D": "Check an employee's availability"
    },
    "answer": "D",
    "explanation_zh": "男士最後說要打電話給司機Milton，看看他是否能改天送貨。因此他下一步是確認員工是否有空。",
    "skill_tag": "listening_next_action",
    "difficulty": "B1",
    "vocabulary": [
      "driver",
      "availability",
      "call"
    ],
    "transcript": "W: Good morning. This is Pamela at Lubbock Sales. You were supposed to deliver some boxes today, but I'm wondering if you can do it tomorrow instead. They're carrying out emergency repairs on our road, so it's difficult to access our entrance.\nM: Don't you need the items urgently?\nW: We can wait another day. They're containers for moving our office items, and we aren't quite ready to start packing anyway.\nM: I see. Then, let me call our driver, Milton, to see if he can do it.",
    "question_order": 3
  },
  {
    "id": "p3-ed-0013",
    "part": "Part 3",
    "question": "Where does the man work?",
    "choices": {
      "A": "At a computer repair shop",
      "B": "At a medical clinic",
      "C": "At a bank",
      "D": "At an employment agency"
    },
    "answer": "B",
    "explanation_zh": "男士接聽電話時說「Good morning, Chapman Health Center」，表示他在健康中心工作，因此正確答案為 (B) At a medical clinic。",
    "skill_tag": "listening_detail",
    "difficulty": "A2",
    "vocabulary": [
      "health center",
      "clinic",
      "receptionist"
    ],
    "transcript": "M: Good morning, Chapman Health Center.\nW: Hi, I have a doctor's appointment on Thursday at ten, but I need to reschedule it.\nM: I can help you with that. Could you please tell me your name?\nW: It's Bonnie Phillips. I'm supposed to have my annual checkup, but now I need to fly to Sacramento for a work conference.\nM: Are you available next Wednesday at nine o'clock?\nW: Yes. Thanks.\nM: Okay. Let's see ... your insurance policy expires in November, right?\nW: I'll have to check. Just a moment.",
    "question_order": 1
  },
  {
    "id": "p3-ed-0014",
    "part": "Part 3",
    "question": "Why does the woman need to make a change?",
    "choices": {
      "A": "She is having car problems.",
      "B": "She will take a business trip.",
      "C": "She must teach a class.",
      "D": "She is not feeling well."
    },
    "answer": "B",
    "explanation_zh": "女士說原本有年度健檢，但「now I need to fly to Sacramento for a work conference」，因此需要更改預約，正確答案為 (B) She will take a business trip。",
    "skill_tag": "listening_detail",
    "difficulty": "B1",
    "vocabulary": [
      "reschedule",
      "annual checkup",
      "work conference"
    ],
    "transcript": "M: Good morning, Chapman Health Center.\nW: Hi, I have a doctor's appointment on Thursday at ten, but I need to reschedule it.\nM: I can help you with that. Could you please tell me your name?\nW: It's Bonnie Phillips. I'm supposed to have my annual checkup, but now I need to fly to Sacramento for a work conference.\nM: Are you available next Wednesday at nine o'clock?\nW: Yes. Thanks.\nM: Okay. Let's see ... your insurance policy expires in November, right?\nW: I'll have to check. Just a moment.",
    "question_order": 2
  },
  {
    "id": "p3-ed-0015",
    "part": "Part 3",
    "question": "What will the woman most likely do next?",
    "choices": {
      "A": "Make a formal complaint",
      "B": "Provide new contact information",
      "C": "Confirm an expiration date",
      "D": "Contact another branch"
    },
    "answer": "C",
    "explanation_zh": "男士問「your insurance policy expires in November, right?」，女士回答「I'll have to check. Just a moment.」，表示她接下來會確認保單到期日，正確答案為 (C) Confirm an expiration date。",
    "skill_tag": "listening_next_action",
    "difficulty": "B1",
    "vocabulary": [
      "insurance policy",
      "expire",
      "expiration date"
    ],
    "transcript": "M: Good morning, Chapman Health Center.\nW: Hi, I have a doctor's appointment on Thursday at ten, but I need to reschedule it.\nM: I can help you with that. Could you please tell me your name?\nW: It's Bonnie Phillips. I'm supposed to have my annual checkup, but now I need to fly to Sacramento for a work conference.\nM: Are you available next Wednesday at nine o'clock?\nW: Yes. Thanks.\nM: Okay. Let's see ... your insurance policy expires in November, right?\nW: I'll have to check. Just a moment.",
    "question_order": 3
  },
  {
    "id": "p3-ed-0016",
    "part": "Part 3",
    "question": "Where do the speakers most likely work?",
    "choices": {
      "A": "At a farm",
      "B": "At a warehouse",
      "C": "At a café",
      "D": "At an appliance store"
    },
    "answer": "C",
    "explanation_zh": "對話中男子提到「menu（菜單）」、「main dishes（主菜）」、「desserts（甜點）」以及「cooks（廚師）」，這些詞彙都與餐飲業相關，因此最可能的工作場所是咖啡廳。",
    "skill_tag": "listening_inference",
    "difficulty": "B1",
    "vocabulary": [
      "menu",
      "main dishes",
      "desserts"
    ],
    "transcript": "M: Christina, most of the feedback on the customer comment cards is positive. However, there were quite a few complaints about our menu being so limited.\nW: I didn't realize that was an issue.\nM: Well, I thought maybe we could add a better variety of main dishes.\nW: Hmm ... All of our cooks would have to learn how to make those, and the training period is already quite long.\nM: Then how about just adding more desserts? Steven makes all of them, so the change wouldn't affect others. I'm sure he could handle it, as he's worked in the industry for a long time.",
    "question_order": 1
  },
  {
    "id": "p3-ed-0017",
    "part": "Part 3",
    "question": "Why does the woman say, \"the training period is already quite long\"?",
    "choices": {
      "A": "To reject a suggestion",
      "B": "To reassure the man",
      "C": "To offer her assistance",
      "D": "To suggest changing a schedule"
    },
    "answer": "A",
    "explanation_zh": "男子提議增加主菜種類，女子回應「the training period is already quite long」，暗示訓練時間已經很長，無法再增加新菜色，因此是用來拒絕男子的建議。",
    "skill_tag": "listening_detail",
    "difficulty": "B1",
    "vocabulary": [
      "training period",
      "suggestion",
      "reject"
    ],
    "transcript": "M: Christina, most of the feedback on the customer comment cards is positive. However, there were quite a few complaints about our menu being so limited.\nW: I didn't realize that was an issue.\nM: Well, I thought maybe we could add a better variety of main dishes.\nW: Hmm ... All of our cooks would have to learn how to make those, and the training period is already quite long.\nM: Then how about just adding more desserts? Steven makes all of them, so the change wouldn't affect others. I'm sure he could handle it, as he's worked in the industry for a long time.",
    "question_order": 2
  },
  {
    "id": "p3-ed-0018",
    "part": "Part 3",
    "question": "What does the man mention about Steven?",
    "choices": {
      "A": "He has a lot of experience.",
      "B": "He is dissatisfied with the work conditions.",
      "C": "He can recommend a supplier.",
      "D": "He may have trouble with a workload."
    },
    "answer": "A",
    "explanation_zh": "男子說「I'm sure he could handle it, as he's worked in the industry for a long time」，直接指出 Steven 在餐飲業工作多年，因此經驗豐富。",
    "skill_tag": "listening_detail",
    "difficulty": "A2",
    "vocabulary": [
      "handle",
      "industry",
      "experience"
    ],
    "transcript": "M: Christina, most of the feedback on the customer comment cards is positive. However, there were quite a few complaints about our menu being so limited.\nW: I didn't realize that was an issue.\nM: Well, I thought maybe we could add a better variety of main dishes.\nW: Hmm ... All of our cooks would have to learn how to make those, and the training period is already quite long.\nM: Then how about just adding more desserts? Steven makes all of them, so the change wouldn't affect others. I'm sure he could handle it, as he's worked in the industry for a long time.",
    "question_order": 3
  },
  {
    "id": "p3-ed-0019",
    "part": "Part 3",
    "question": "Where are the speakers?",
    "choices": {
      "A": "At a movie theater",
      "B": "At a library",
      "C": "At a restaurant",
      "D": "At a gym"
    },
    "answer": "D",
    "explanation_zh": "對話開頭男士問「你有我們健身房的通行證嗎？」，女士回答還未取得，並想了解課程，後續也提到團體課程與會員費，因此場景為健身房。",
    "skill_tag": "listening_main_idea",
    "difficulty": "A2",
    "vocabulary": [
      "pass",
      "gym",
      "membership fees"
    ],
    "transcript": "M1: Good afternoon. Do you have a pass to our gym?\nW: Not yet. I'd like to know more about your classes.\nM1: Of course. My colleague can tell you more.\n Joseph, could you please explain our system for group exercise classes?\nM2: Sure. You can sign up online and attend up to five per week. These are included in your membership fees.\nW: That's great. Also, I heard that you give discounts to Wesley Sales employees. I just began working there last month. Am I eligible?",
    "question_order": 1
  },
  {
    "id": "p3-ed-0020",
    "part": "Part 3",
    "question": "What does Joseph give the woman information about?",
    "choices": {
      "A": "Meeting staff members",
      "B": "Participating in group classes",
      "C": "Accessing an account",
      "D": "Touring a facility"
    },
    "answer": "B",
    "explanation_zh": "男士 Joseph 被要求解釋團體運動課程的系統，他說明可以線上報名並每週參加最多五堂課，這些包含在會員費中，因此他提供的是關於參加團體課程的資訊。",
    "skill_tag": "listening_detail",
    "difficulty": "B1",
    "vocabulary": [
      "sign up",
      "group exercise classes",
      "attend"
    ],
    "transcript": "M1: Good afternoon. Do you have a pass to our gym?\nW: Not yet. I'd like to know more about your classes.\nM1: Of course. My colleague can tell you more.\n Joseph, could you please explain our system for group exercise classes?\nM2: Sure. You can sign up online and attend up to five per week. These are included in your membership fees.\nW: That's great. Also, I heard that you give discounts to Wesley Sales employees. I just began working there last month. Am I eligible?",
    "question_order": 2
  },
  {
    "id": "p3-ed-0021",
    "part": "Part 3",
    "question": "What does the woman say she did last month?",
    "choices": {
      "A": "She moved to a different city.",
      "B": "She started a new job.",
      "C": "She received a certification.",
      "D": "She began studying online."
    },
    "answer": "B",
    "explanation_zh": "女士說「我上個月才開始在那裡工作」，對應到她提到 Wesley Sales 員工有折扣，並詢問自己是否符合資格，因此她上個月開始了新工作。",
    "skill_tag": "listening_detail",
    "difficulty": "A2",
    "vocabulary": [
      "eligible",
      "employee",
      "discount"
    ],
    "transcript": "M1: Good afternoon. Do you have a pass to our gym?\nW: Not yet. I'd like to know more about your classes.\nM1: Of course. My colleague can tell you more.\n Joseph, could you please explain our system for group exercise classes?\nM2: Sure. You can sign up online and attend up to five per week. These are included in your membership fees.\nW: That's great. Also, I heard that you give discounts to Wesley Sales employees. I just began working there last month. Am I eligible?",
    "question_order": 3
  },
  {
    "id": "p3-ed-0022",
    "part": "Part 3",
    "question": "What industry do the speakers most likely work in?",
    "choices": {
      "A": "Advertising",
      "B": "Technology",
      "C": "Energy",
      "D": "Pharmaceuticals"
    },
    "answer": "B",
    "explanation_zh": "對話中男士提到「software programs」和「programmers」，女士則說要「remain competitive」並吸引「top talent」，這些關鍵詞都指向科技產業，因此最可能的工作行業是科技業。",
    "skill_tag": "listening_main_idea",
    "difficulty": "B1",
    "vocabulary": [
      "software programs",
      "programmers",
      "competitive"
    ],
    "transcript": "M: Demand for our software programs is still growing, Danielle. We need to expand our team of programmers, but we're having a lot of problems filling the positions.\nW: You know, if we want to remain competitive, we need to increase the annual salary we offer to the staff. That would help to retain good workers as well as attract the top talent for new workers.\nM: That sounds like a good idea, but would our current situation support that change?\nW: I believe so, since our sales have been strong.\n I'll look over our budget categories to see what's possible.",
    "question_order": 1
  },
  {
    "id": "p3-ed-0023",
    "part": "Part 3",
    "question": "What change are the speakers discussing?",
    "choices": {
      "A": "Relocating to another site",
      "B": "Purchasing some machinery",
      "C": "Extending the hours of operation",
      "D": "Raising salaries for employees"
    },
    "answer": "D",
    "explanation_zh": "女士明確建議「increase the annual salary we offer to the staff」，並說明這能留住好員工及吸引頂尖人才，因此討論的改變是提高員工薪資。",
    "skill_tag": "listening_detail",
    "difficulty": "B1",
    "vocabulary": [
      "annual salary",
      "retain",
      "attract"
    ],
    "transcript": "M: Demand for our software programs is still growing, Danielle. We need to expand our team of programmers, but we're having a lot of problems filling the positions.\nW: You know, if we want to remain competitive, we need to increase the annual salary we offer to the staff. That would help to retain good workers as well as attract the top talent for new workers.\nM: That sounds like a good idea, but would our current situation support that change?\nW: I believe so, since our sales have been strong.\n I'll look over our budget categories to see what's possible.",
    "question_order": 2
  },
  {
    "id": "p3-ed-0024",
    "part": "Part 3",
    "question": "What does the woman offer to do?",
    "choices": {
      "A": "Set up some sale items",
      "B": "Contact a specialist",
      "C": "Review some financial data",
      "D": "Gather feedback from the staff"
    },
    "answer": "C",
    "explanation_zh": "女士在對話結尾說「I'll look over our budget categories to see what's possible」，意思是她會檢視預算類別，即審查財務數據，因此她主動提出要檢視一些財務資料。",
    "skill_tag": "listening_detail",
    "difficulty": "B1",
    "vocabulary": [
      "budget categories",
      "look over",
      "financial data"
    ],
    "transcript": "M: Demand for our software programs is still growing, Danielle. We need to expand our team of programmers, but we're having a lot of problems filling the positions.\nW: You know, if we want to remain competitive, we need to increase the annual salary we offer to the staff. That would help to retain good workers as well as attract the top talent for new workers.\nM: That sounds like a good idea, but would our current situation support that change?\nW: I believe so, since our sales have been strong.\n I'll look over our budget categories to see what's possible.",
    "question_order": 3
  },
  {
    "id": "p3-ed-0025",
    "part": "Part 3",
    "question": "What problem is the man calling about?",
    "choices": {
      "A": "He has forgotten a password.",
      "B": "He provided some incorrect\ninformation.",
      "C": "He lost his most recent bill.",
      "D": "He has been overcharged."
    },
    "answer": "D",
    "explanation_zh": "男子說他被收了兩倍正常金額的費用，並提到「I've been charged twice my normal amount」，因此問題是他被多收費了。",
    "skill_tag": "listening_main_idea",
    "difficulty": "B1",
    "vocabulary": [
      "overcharge",
      "bill",
      "charged"
    ],
    "transcript": "M: Hi, I'm calling because I just got my bill for\nSeptember and there's an issue. I've been\ncharged twice my normal amount.\n\nW: I'm sorry about that, sir. Our Internet company\nstrives to ensure accuracy. Could you please\ntell me your account number?\n\nM: Yes, it's 47801. I moved to a new home on\nthe fifteenth of last month, and it looks like I've\nbeen charged the full fee at both places.\n\nW: I see. Please wait while I look into this further.",
    "question_order": 1
  },
  {
    "id": "p3-ed-0026",
    "part": "Part 3",
    "question": "Where does the woman work?",
    "choices": {
      "A": "At a shipping service",
      "B": "At a moving company",
      "C": "At an Internet provider",
      "D": "At an accounting firm"
    },
    "answer": "C",
    "explanation_zh": "女子在對話中說「Our Internet company strives to ensure accuracy」，直接表明她任職於一家網路公司。",
    "skill_tag": "listening_detail",
    "difficulty": "B1",
    "vocabulary": [
      "Internet provider",
      "strive",
      "accuracy"
    ],
    "transcript": "M: Hi, I'm calling because I just got my bill for\nSeptember and there's an issue. I've been\ncharged twice my normal amount.\n\nW: I'm sorry about that, sir. Our Internet company\nstrives to ensure accuracy. Could you please\ntell me your account number?\n\nM: Yes, it's 47801. I moved to a new home on\nthe fifteenth of last month, and it looks like I've\nbeen charged the full fee at both places.\n\nW: I see. Please wait while I look into this further.",
    "question_order": 2
  },
  {
    "id": "p3-ed-0027",
    "part": "Part 3",
    "question": "What did the man do last month?",
    "choices": {
      "A": "He moved to a new address.",
      "B": "He upgraded a service package.",
      "C": "He launched his own business.",
      "D": "He visited the woman's company."
    },
    "answer": "A",
    "explanation_zh": "男子提到「I moved to a new home on the fifteenth of last month」，明確指出他上個月搬了新家。",
    "skill_tag": "listening_detail",
    "difficulty": "A2",
    "vocabulary": [
      "move",
      "address",
      "last month"
    ],
    "transcript": "M: Hi, I'm calling because I just got my bill for\nSeptember and there's an issue. I've been\ncharged twice my normal amount.\n\nW: I'm sorry about that, sir. Our Internet company\nstrives to ensure accuracy. Could you please\ntell me your account number?\n\nM: Yes, it's 47801. I moved to a new home on\nthe fifteenth of last month, and it looks like I've\nbeen charged the full fee at both places.\n\nW: I see. Please wait while I look into this further.",
    "question_order": 3
  },
  {
    "id": "p3-ed-0028",
    "part": "Part 3",
    "question": "What are the speakers discussing?",
    "choices": {
      "A": "A job opening",
      "B": "A product release",
      "C": "A company relocation",
      "D": "An annual event"
    },
    "answer": "A",
    "explanation_zh": "對話開頭女士提到「software developer position that my team is currently interviewing candidates for」，並討論應徵者經驗不足、需要擴大應徵者池，因此整段對話核心是關於一個職缺。",
    "skill_tag": "listening_main_idea",
    "difficulty": "B1",
    "vocabulary": [
      "software developer",
      "position",
      "applicant pool"
    ],
    "transcript": "W: Good morning, Andrew. I want to talk to you\nabout the software developer position that my\nteam is currently interviewing candidates for.\n\nM: Sure. What's up?\n\nW: So far, none of the applicants we've seen have\nhad sufficient experience in web development.\nI think we need to expand the applicant pool.\nCan HR increase the salary listed in the job\nposting?\n\nM: I'll need to discuss it with my team members.\nHow soon do you need a response?\n\nW: Well, the project manager has already moved\nup our deadline.\n\nM: Understood. I'll e-mail you as soon as a\ndecision is reached.",
    "question_order": 1
  },
  {
    "id": "p3-ed-0029",
    "part": "Part 3",
    "question": "What department does the woman most likely work in?",
    "choices": {
      "A": "Finance",
      "B": "Marketing",
      "C": "Information technology",
      "D": "Operations management"
    },
    "answer": "C",
    "explanation_zh": "女士負責面試軟體開發人員，並提到需要增加網頁開發經驗的應徵者，這與資訊科技部門的職責直接相關。",
    "skill_tag": "listening_inference",
    "difficulty": "B1",
    "vocabulary": [
      "software developer",
      "web development",
      "department"
    ],
    "transcript": "W: Good morning, Andrew. I want to talk to you\nabout the software developer position that my\nteam is currently interviewing candidates for.\n\nM: Sure. What's up?\n\nW: So far, none of the applicants we've seen have\nhad sufficient experience in web development.\nI think we need to expand the applicant pool.\nCan HR increase the salary listed in the job\nposting?\n\nM: I'll need to discuss it with my team members.\nHow soon do you need a response?\n\nW: Well, the project manager has already moved\nup our deadline.\n\nM: Understood. I'll e-mail you as soon as a\ndecision is reached.",
    "question_order": 2
  },
  {
    "id": "p3-ed-0030",
    "part": "Part 3",
    "question": "Why does the woman say, \"The project manager has already moved up our deadline\"?",
    "choices": {
      "A": "To demonstrate urgency",
      "B": "To show appreciation",
      "C": "To propose a compromise",
      "D": "To express confusion"
    },
    "answer": "A",
    "explanation_zh": "女士說「專案經理已經提前了截止日期」，目的是向男士說明為何需要盡快獲得加薪決定的回覆，以強調時間緊迫。",
    "skill_tag": "listening_detail",
    "difficulty": "B1",
    "vocabulary": [
      "project manager",
      "deadline",
      "urgency"
    ],
    "transcript": "W: Good morning, Andrew. I want to talk to you\nabout the software developer position that my\nteam is currently interviewing candidates for.\n\nM: Sure. What's up?\n\nW: So far, none of the applicants we've seen have\nhad sufficient experience in web development.\nI think we need to expand the applicant pool.\nCan HR increase the salary listed in the job\nposting?\n\nM: I'll need to discuss it with my team members.\nHow soon do you need a response?\n\nW: Well, the project manager has already moved\nup our deadline.\n\nM: Understood. I'll e-mail you as soon as a\ndecision is reached.",
    "question_order": 3
  },
  {
    "id": "p4-ed-0001",
    "part": "Part 4",
    "question": "What is the podcast episode about?",
    "choices": {
      "A": "Online advertising",
      "B": "Computer programming",
      "C": "Starting a business",
      "D": "Expanding overseas"
    },
    "answer": "A",
    "explanation_zh": "題目問本集 podcast 的主題是什麼。講者開頭提到「digital self-promotion」及「viral marketing campaign」，這些都屬於線上廣告的範疇，因此正確答案為 (A) Online advertising。",
    "skill_tag": "listening_main_idea",
    "difficulty": "B1",
    "vocabulary": [
      "digital self-promotion",
      "viral marketing campaign"
    ],
    "transcript": "M: Welcome back to the Entrepreneurial Ventures podcast. Today, my topic is digital self-promotion. When is the right time to start a new viral marketing campaign, and how can you do so effectively in the modern world? To answer these questions and more, I'll be introducing a special guest: Amara Dambe. The founder of the famous tech start-up, Financing Together, Ms. Dambe is known for her ability to get into the mentalities of consumers when they're using virtual spaces. I think you'll enjoy this episode. But before getting started, I'm going to briefly talk about a new service that I'm offering for a small monthly fee.\n\nW: 77Next Monday, we'll have the first in a series of seminars about reducing stress in the workplace. Our first guest lecturer will help you learn to use meditative breathing exercises to calm your body and mind. 78I was inspired to launch this series when I read a recent news story about the effects of physical and mental health on employee productivity. As part of the initiative, we've also started installing mood-enhancing lighting throughout the building. 79I'm distributing a pamphlet that talks about the scientific reason for the change.",
    "question_order": 1
  },
  {
    "id": "p4-ed-0002",
    "part": "Part 4",
    "question": "What does the speaker say Ms. Dambe is good at?",
    "choices": {
      "A": "Solving technical glitches",
      "B": "Getting funding",
      "C": "Understanding customers",
      "D": "Negotiating with suppliers"
    },
    "answer": "C",
    "explanation_zh": "題目問講者說 Ms. Dambe 擅長什麼。原文提到「Ms. Dambe is known for her ability to get into the mentalities of consumers」，即她擅長理解消費者的心態，因此正確答案為 (C) Understanding customers。",
    "skill_tag": "listening_detail",
    "difficulty": "B1",
    "vocabulary": [
      "mentalities",
      "consumers",
      "virtual spaces"
    ],
    "transcript": "M: Welcome back to the Entrepreneurial Ventures podcast. Today, my topic is digital self-promotion. When is the right time to start a new viral marketing campaign, and how can you do so effectively in the modern world? To answer these questions and more, I'll be introducing a special guest: Amara Dambe. The founder of the famous tech start-up, Financing Together, Ms. Dambe is known for her ability to get into the mentalities of consumers when they're using virtual spaces. I think you'll enjoy this episode. But before getting started, I'm going to briefly talk about a new service that I'm offering for a small monthly fee.\n\nW: 77Next Monday, we'll have the first in a series of seminars about reducing stress in the workplace. Our first guest lecturer will help you learn to use meditative breathing exercises to calm your body and mind. 78I was inspired to launch this series when I read a recent news story about the effects of physical and mental health on employee productivity. As part of the initiative, we've also started installing mood-enhancing lighting throughout the building. 79I'm distributing a pamphlet that talks about the scientific reason for the change.",
    "question_order": 2
  },
  {
    "id": "p4-ed-0003",
    "part": "Part 4",
    "question": "What will the speaker discuss next?",
    "choices": {
      "A": "A subscription service",
      "B": "A research project",
      "C": "A listener question",
      "D": "A news report"
    },
    "answer": "A",
    "explanation_zh": "題目問講者接下來要討論什麼。原文最後一句說「I'm going to briefly talk about a new service that I'm offering for a small monthly fee」，這是一項需付費的訂閱服務，因此正確答案為 (A) A subscription service。",
    "skill_tag": "listening_next_action",
    "difficulty": "B1",
    "vocabulary": [
      "monthly fee",
      "subscription service"
    ],
    "transcript": "M: Welcome back to the Entrepreneurial Ventures podcast. Today, my topic is digital self-promotion. When is the right time to start a new viral marketing campaign, and how can you do so effectively in the modern world? To answer these questions and more, I'll be introducing a special guest: Amara Dambe. The founder of the famous tech start-up, Financing Together, Ms. Dambe is known for her ability to get into the mentalities of consumers when they're using virtual spaces. I think you'll enjoy this episode. But before getting started, I'm going to briefly talk about a new service that I'm offering for a small monthly fee.\n\nW: 77Next Monday, we'll have the first in a series of seminars about reducing stress in the workplace. Our first guest lecturer will help you learn to use meditative breathing exercises to calm your body and mind. 78I was inspired to launch this series when I read a recent news story about the effects of physical and mental health on employee productivity. As part of the initiative, we've also started installing mood-enhancing lighting throughout the building. 79I'm distributing a pamphlet that talks about the scientific reason for the change.",
    "question_order": 3
  },
  {
    "id": "p4-ed-0004",
    "part": "Part 4",
    "question": "What type of business is the listener calling?",
    "choices": {
      "A": "A cable provider",
      "B": "A consulting company",
      "C": "A utility company",
      "D": "An automobile manufacturer"
    },
    "answer": "C",
    "explanation_zh": "錄音稿開頭提到「Blandensville County Power Company」，且內容涉及電線桿倒塌、電網更新，因此這是一家電力公司，屬於公用事業公司。選項 (C) A utility company 正確對應此類業務。",
    "skill_tag": "listening_main_idea",
    "difficulty": "A2",
    "vocabulary": [
      "utility company",
      "power company",
      "electric grid"
    ],
    "transcript": "W: Good afternoon. You've reached the Blandensville County Power Company. Please note that a telephone pole was recently knocked down near McArthur Avenue as a result of a traffic accident. A team of responders is on site. We thank you for your patience. If you'd like to receive updates about the electric grid in your area, press 1 to sign up for our automatic texting service.",
    "question_order": 1
  },
  {
    "id": "p4-ed-0005",
    "part": "Part 4",
    "question": "What does the speaker imply when she says, \"We thank you for your patience\"?",
    "choices": {
      "A": "The responders are untrained.",
      "B": "The company is closing soon.",
      "C": "Many people are complaining.",
      "D": "The repairs are not yet complete."
    },
    "answer": "D",
    "explanation_zh": "說話者先說明電線桿因事故倒塌，並表示維修團隊已在現場，接著說「感謝您的耐心」，暗示維修尚未完成，需要顧客等候。因此正確答案為 (D) The repairs are not yet complete。",
    "skill_tag": "listening_inference",
    "difficulty": "B1",
    "vocabulary": [
      "patience",
      "responders",
      "repairs"
    ],
    "transcript": "W: Good afternoon. You've reached the Blandensville County Power Company. Please note that a telephone pole was recently knocked down near McArthur Avenue as a result of a traffic accident. A team of responders is on site. We thank you for your patience. If you'd like to receive updates about the electric grid in your area, press 1 to sign up for our automatic texting service.",
    "question_order": 2
  },
  {
    "id": "p4-ed-0006",
    "part": "Part 4",
    "question": "How can the listener stay updated?",
    "choices": {
      "A": "By getting automated e-mails",
      "B": "By calling again later",
      "C": "By receiving text messages",
      "D": "By checking a website"
    },
    "answer": "C",
    "explanation_zh": "錄音稿最後明確提到「press 1 to sign up for our automatic texting service」，表示顧客可透過接收簡訊獲得更新。因此正確答案為 (C) By receiving text messages。",
    "skill_tag": "listening_detail",
    "difficulty": "A2",
    "vocabulary": [
      "texting service",
      "sign up",
      "updates"
    ],
    "transcript": "W: Good afternoon. You've reached the Blandensville County Power Company. Please note that a telephone pole was recently knocked down near McArthur Avenue as a result of a traffic accident. A team of responders is on site. We thank you for your patience. If you'd like to receive updates about the electric grid in your area, press 1 to sign up for our automatic texting service.",
    "question_order": 3
  },
  {
    "id": "p4-ed-0007",
    "part": "Part 4",
    "question": "Why have some citizens complained?",
    "choices": {
      "A": "Street parking is unavailable.",
      "B": "The roads are damaged.",
      "C": "Street cleaning is too infrequent.",
      "D": "Parking garages are too expensive."
    },
    "answer": "B",
    "explanation_zh": "聽力稿中提到「a group of citizens submitted a petition to repair and repave a number of the town's streets」，並指出「Main Street has been reported as a dangerous area due to the presence of potholes」，因此居民抱怨的原因是道路受損。",
    "skill_tag": "listening_detail",
    "difficulty": "A2",
    "vocabulary": [
      "petition",
      "repave",
      "pothole"
    ],
    "transcript": "W: The City Council will now discuss the issue of street maintenance. A group of citizens submitted a petition to repair and repave a number of the town's streets. In particular, Main Street has been reported as a dangerous area due to the presence of potholes in various locations. While the motion has been approved, Chairperson John Daly has raised a concern that the requested work will be obtrusively loud for Main Street residents. To compensate these residents, the city will reimburse up to a one week stay at the nearby Comfort Plus Inn for those who live within a 50-meter radius of the work site.",
    "question_order": 1
  },
  {
    "id": "p4-ed-0008",
    "part": "Part 4",
    "question": "What is John Daly concerned about?",
    "choices": {
      "A": "Higher taxes",
      "B": "Environmental damage",
      "C": "Increased traffic",
      "D": "Construction noise"
    },
    "answer": "D",
    "explanation_zh": "聽力稿中明確指出「Chairperson John Daly has raised a concern that the requested work will be obtrusively loud for Main Street residents」，因此他擔心的是施工噪音。",
    "skill_tag": "listening_detail",
    "difficulty": "A2",
    "vocabulary": [
      "obtrusively",
      "concern",
      "resident"
    ],
    "transcript": "W: The City Council will now discuss the issue of street maintenance. A group of citizens submitted a petition to repair and repave a number of the town's streets. In particular, Main Street has been reported as a dangerous area due to the presence of potholes in various locations. While the motion has been approved, Chairperson John Daly has raised a concern that the requested work will be obtrusively loud for Main Street residents. To compensate these residents, the city will reimburse up to a one week stay at the nearby Comfort Plus Inn for those who live within a 50-meter radius of the work site.",
    "question_order": 2
  },
  {
    "id": "p4-ed-0009",
    "part": "Part 4",
    "question": "What will certain residents receive?",
    "choices": {
      "A": "Parking passes",
      "B": "Hotel room fees",
      "C": "Event tickets",
      "D": "Transportation services"
    },
    "answer": "B",
    "explanation_zh": "聽力稿最後提到「the city will reimburse up to a one week stay at the nearby Comfort Plus Inn for those who live within a 50-meter radius of the work site」，因此特定居民將獲得旅館住宿費用的補償。",
    "skill_tag": "listening_detail",
    "difficulty": "B1",
    "vocabulary": [
      "reimburse",
      "radius",
      "stay"
    ],
    "transcript": "W: The City Council will now discuss the issue of street maintenance. A group of citizens submitted a petition to repair and repave a number of the town's streets. In particular, Main Street has been reported as a dangerous area due to the presence of potholes in various locations. While the motion has been approved, Chairperson John Daly has raised a concern that the requested work will be obtrusively loud for Main Street residents. To compensate these residents, the city will reimburse up to a one week stay at the nearby Comfort Plus Inn for those who live within a 50-meter radius of the work site.",
    "question_order": 3
  },
  {
    "id": "p4-ed-0010",
    "part": "Part 4",
    "question": "What is the topic of the seminar?",
    "choices": {
      "A": "Manufacturing",
      "B": "Shipping",
      "C": "Publishing",
      "D": "Journalism"
    },
    "answer": "C",
    "explanation_zh": "講者開場即說明本場研討會的主題是「the future of publishers」，因此主題與出版業相關。正確答案為 (C) Publishing。",
    "skill_tag": "listening_main_idea",
    "difficulty": "A2",
    "vocabulary": [
      "publisher",
      "seminar",
      "paperless society"
    ],
    "transcript": "M: Hi! Welcome to today's seminar about the future of publishers in our increasingly paperless society. I'm Jean Couturier, and I've been working in the publishing industry for over thirty years. Before I get started, I want to thank those of you who submitted anonymous inquiries through my website. Those questions helped me design my slides for today's presentation. I also want to express my gratitude for my assistant, Melanie Grichuk, who worked hard to make this event happen. There's Melanie in the back corner—let's give her a round of applause.",
    "question_order": 1
  },
  {
    "id": "p4-ed-0011",
    "part": "Part 4",
    "question": "Why does the speaker thank some of the listeners?",
    "choices": {
      "A": "They raised questions.",
      "B": "They shared their experience.",
      "C": "They attended previous talks.",
      "D": "They gave feedback on the slides."
    },
    "answer": "A",
    "explanation_zh": "講者感謝那些透過他的網站提交匿名問題的聽眾，因為這些問題幫助他設計投影片。正確答案為 (A) They raised questions。",
    "skill_tag": "listening_detail",
    "difficulty": "B1",
    "vocabulary": [
      "anonymous inquiry",
      "submit",
      "presentation"
    ],
    "transcript": "M: Hi! Welcome to today's seminar about the future of publishers in our increasingly paperless society. I'm Jean Couturier, and I've been working in the publishing industry for over thirty years. Before I get started, I want to thank those of you who submitted anonymous inquiries through my website. Those questions helped me design my slides for today's presentation. I also want to express my gratitude for my assistant, Melanie Grichuk, who worked hard to make this event happen. There's Melanie in the back corner—let's give her a round of applause.",
    "question_order": 2
  },
  {
    "id": "p4-ed-0012",
    "part": "Part 4",
    "question": "Why does the speaker mention the back of the room?",
    "choices": {
      "A": "Refreshments are available there.",
      "B": "A worker is sitting there.",
      "C": "Informational materials are there.",
      "D": "A book is on sale there."
    },
    "answer": "B",
    "explanation_zh": "講者提到「There's Melanie in the back corner」，表示他的助理梅蘭妮坐在後方角落，因此提及房間後方是因為有位工作人員坐在那裡。正確答案為 (B) A worker is sitting there。",
    "skill_tag": "listening_detail",
    "difficulty": "A2",
    "vocabulary": [
      "assistant",
      "round of applause",
      "back corner"
    ],
    "transcript": "M: Hi! Welcome to today's seminar about the future of publishers in our increasingly paperless society. I'm Jean Couturier, and I've been working in the publishing industry for over thirty years. Before I get started, I want to thank those of you who submitted anonymous inquiries through my website. Those questions helped me design my slides for today's presentation. I also want to express my gratitude for my assistant, Melanie Grichuk, who worked hard to make this event happen. There's Melanie in the back corner—let's give her a round of applause.",
    "question_order": 3
  },
  {
    "id": "p4-ed-0013",
    "part": "Part 4",
    "question": "Why is Matteo away from his business?",
    "choices": {
      "A": "He is meeting a supplier.",
      "B": "He is delivering a lecture.",
      "C": "He is at a job interview.",
      "D": "He is viewing real estate."
    },
    "answer": "B",
    "explanation_zh": "錄音稿開頭提到「I hope your university talk goes well tonight」，表示Matteo今晚有一場大學演講，因此他離開餐廳是為了去演講。選項(B) He is delivering a lecture 符合此意。",
    "skill_tag": "listening_detail",
    "difficulty": "A2",
    "vocabulary": [
      "university talk",
      "go well",
      "away"
    ],
    "transcript": "W: Hi, Matteo. I hope your university talk goes well tonight. Everything's fine here at Vezia Bistro while you're away, but I want to follow up on the instructions you left behind. I know you wanted to offer chicken marsala as our weekly special, but some of the supplies for that dish are running low. Fettuccini alfredo has always been a hit with our regulars. Also, I've got good news. An influential blogger visited the restaurant last night and wrote up some major praise for us on his site this morning.",
    "question_order": 1
  },
  {
    "id": "p4-ed-0014",
    "part": "Part 4",
    "question": "Why does the speaker say, \"Fettuccini alfredo has always been a hit with our regulars\"?",
    "choices": {
      "A": "To make a suggestion",
      "B": "To provide a compliment",
      "C": "To demonstrate a problem",
      "D": "To congratulate an achievement"
    },
    "answer": "A",
    "explanation_zh": "說話者先提到原本想提供的雞肉馬沙拉食材不足，接著說「Fettuccini alfredo has always been a hit with our regulars」，暗示可以改用這道受歡迎的料理作為替代方案，目的是提出建議。因此正確答案為 (A) To make a suggestion。",
    "skill_tag": "listening_inference",
    "difficulty": "B1",
    "vocabulary": [
      "a hit with",
      "regulars",
      "suggestion"
    ],
    "transcript": "W: Hi, Matteo. I hope your university talk goes well tonight. Everything's fine here at Vezia Bistro while you're away, but I want to follow up on the instructions you left behind. I know you wanted to offer chicken marsala as our weekly special, but some of the supplies for that dish are running low. Fettuccini alfredo has always been a hit with our regulars. Also, I've got good news. An influential blogger visited the restaurant last night and wrote up some major praise for us on his site this morning.",
    "question_order": 2
  },
  {
    "id": "p4-ed-0015",
    "part": "Part 4",
    "question": "What good news does the speaker share about the restaurant?",
    "choices": {
      "A": "It won an annual award.",
      "B": "It had an influx of customers.",
      "C": "It received attention online.",
      "D": "It appeared in a television show."
    },
    "answer": "C",
    "explanation_zh": "錄音稿結尾提到「An influential blogger visited the restaurant last night and wrote up some major praise for us on his site this morning」，表示餐廳獲得部落格上的正面評價，屬於網路上的關注。因此正確答案為 (C) It received attention online。",
    "skill_tag": "listening_detail",
    "difficulty": "A2",
    "vocabulary": [
      "influential blogger",
      "major praise",
      "site"
    ],
    "transcript": "W: Hi, Matteo. I hope your university talk goes well tonight. Everything's fine here at Vezia Bistro while you're away, but I want to follow up on the instructions you left behind. I know you wanted to offer chicken marsala as our weekly special, but some of the supplies for that dish are running low. Fettuccini alfredo has always been a hit with our regulars. Also, I've got good news. An influential blogger visited the restaurant last night and wrote up some major praise for us on his site this morning.",
    "question_order": 3
  },
  {
    "id": "p4-ed-0016",
    "part": "Part 4",
    "question": "What type of business does the speaker most likely work at?",
    "choices": {
      "A": "A hardware store",
      "B": "A construction company",
      "C": "A furniture store",
      "D": "A delivery service"
    },
    "answer": "C",
    "explanation_zh": "講者提到新到的 Delillo 床架與層架組、以及所有餐桌椅組正在特價，這些都是家具類商品，因此可推斷他工作的場所是家具店。",
    "skill_tag": "listening_main_idea",
    "difficulty": "B1",
    "vocabulary": [
      "shelving units",
      "dining sets",
      "on sale"
    ],
    "transcript": "M: Hello everyone. We've got a busy week ahead, with the new Delillo models of beds and shelving units arriving soon, and all of our dining sets on sale. There should be plenty of customers streaming in. Now, with Enrico having moved on to another company, we're short-staffed until we find his replacement. But don't worry: , even though most of you haven't seen it. I also need to mention that the back room is starting to get disorganized.",
    "question_order": 1
  },
  {
    "id": "p4-ed-0017",
    "part": "Part 4",
    "question": "What does the speaker imply when he says, \"I have experience in sales\"?",
    "choices": {
      "A": "He will mentor some employees.",
      "B": "He will take over for some shifts.",
      "C": "He will interview candidates soon.",
      "D": "He will offer extra pay for overtime work."
    },
    "answer": "B",
    "explanation_zh": "講者說「我有銷售經驗」後，緊接著說「即使你們大多數人都沒見過」，暗示他會親自站櫃或接手部分班次來補足人力缺口，因此正確答案為 (B) He will take over for some shifts。",
    "skill_tag": "listening_inference",
    "difficulty": "B2",
    "vocabulary": [
      "short-staffed",
      "replacement",
      "experience in sales"
    ],
    "transcript": "M: Hello everyone. We've got a busy week ahead, with the new Delillo models of beds and shelving units arriving soon, and all of our dining sets on sale. There should be plenty of customers streaming in. Now, with Enrico having moved on to another company, we're short-staffed until we find his replacement. But don't worry: , even though most of you haven't seen it. I also need to mention that the back room is starting to get disorganized.",
    "question_order": 2
  },
  {
    "id": "p4-ed-0018",
    "part": "Part 4",
    "question": "What does the speaker expect the listeners to do?",
    "choices": {
      "A": "Reorganize the store layout",
      "B": "Clean an area",
      "C": "Organize a luncheon",
      "D": "Plan a hiring event"
    },
    "answer": "B",
    "explanation_zh": "講者最後提到「後面房間開始變得雜亂無章」，並用「我也需要提一下」帶出，暗示聽眾需要去整理那個區域，因此正確答案為 (B) Clean an area。",
    "skill_tag": "listening_detail",
    "difficulty": "B1",
    "vocabulary": [
      "back room",
      "disorganized",
      "mention"
    ],
    "transcript": "M: Hello everyone. We've got a busy week ahead, with the new Delillo models of beds and shelving units arriving soon, and all of our dining sets on sale. There should be plenty of customers streaming in. Now, with Enrico having moved on to another company, we're short-staffed until we find his replacement. But don't worry: , even though most of you haven't seen it. I also need to mention that the back room is starting to get disorganized.",
    "question_order": 3
  }
];
