// Generated by npm run questions -- sync. Edit question-bank-manifest.json instead.
import type { QuestionBankSource } from "@/lib/questions/catalog";
import { QUESTIONS_PART5 as bank0 } from "./questions-part5";
import { QUESTIONS_PART6 as bank1 } from "./questions-part6";
import { QUESTIONS_PART7 as bank2 } from "./questions-part7";
import { QUESTIONS_LISTENING as bank3 } from "./questions-listening";
import { GENERATED_QUESTIONS as bank4 } from "./questions-generated";
import { IMPORTED_QUESTIONS_XD as bank5 } from "./questions-imported-xd";
import { IMPORTED_QUESTIONS_ED as bank6 } from "./questions-imported-ed";
import { IMPORTED_LISTENING_ED as bank7 } from "./questions-imported-ed-listening";
import { QUESTIONS_PART7_TRIPLE as bank8 } from "./questions-part7-triple";
import { QUESTIONS_PART2_INDIRECT as bank9 } from "./questions-part2-indirect";
import { QUESTIONS_LISTENING_EXTRA as bank10 } from "./questions-listening-extra";

export const QUESTION_BANK_SOURCES: QuestionBankSource[] = [
  { id: "part5", title: "核心 Part 5", questions: bank0 },
  { id: "part6", title: "核心 Part 6", questions: bank1 },
  { id: "part7", title: "核心 Part 7", questions: bank2 },
  { id: "listening", title: "核心聽力", questions: bank3 },
  { id: "generated", title: "生成與擴充題庫", questions: bank4 },
  { id: "imported-xd", title: "XD 閱讀題庫", questions: bank5 },
  { id: "imported-ed", title: "ED 閱讀題庫", questions: bank6 },
  { id: "imported-ed-listening", title: "ED 聽力題庫", questions: bank7 },
  { id: "part7-triple", title: "Part 7 三篇閱讀", questions: bank8 },
  { id: "part2-indirect", title: "Part 2 間接應答", questions: bank9 },
  { id: "listening-extra", title: "補充聽力", questions: bank10 },
];
