/**
 * Provision the cross-device sync credentials.
 *
 * Default (production) mode — run this yourself in a terminal:
 *   npx tsx scripts/sync-setup.ts [--push-env]
 * Generates a random access code (shown ONCE — store it in your password
 * manager; you type it when logging in on each device), writes the scrypt
 * hash + a fresh session secret into .env.local (append/patch — never
 * touches other lines), and with --push-env also pushes both values to
 * Vercel production env via the vercel CLI (values piped over stdin, never
 * argv). Redeploy afterwards so production picks them up.
 *
 * --dev mode (used by local testing): fixed, deliberately NON-secret code
 * "dev-code-not-secret" so localhost E2E can log in without a real secret
 * ever entering logs or transcripts.
 */
import { randomBytes, scryptSync } from "node:crypto";
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { spawnSync } from "node:child_process";
import path from "node:path";

const SCRYPT_N = 16384;
const SCRYPT_R = 8;
const SCRYPT_P = 1;
const KEY_LENGTH = 32;
// No confusable characters (0/O, 1/I/L…) — this gets typed on a phone.
const CODE_ALPHABET = "ABCDEFGHJKMNPQRSTVWXYZ23456789";

function generateAccessCode(): string {
  const bytes = randomBytes(16);
  const chars = Array.from(bytes, (b) => CODE_ALPHABET[b % CODE_ALPHABET.length]);
  return [0, 4, 8, 12]
    .map((start) => chars.slice(start, start + 4).join(""))
    .join("-");
}

function hashAccessCode(code: string): string {
  const salt = randomBytes(16);
  const hash = scryptSync(code, salt, KEY_LENGTH, {
    N: SCRYPT_N,
    r: SCRYPT_R,
    p: SCRYPT_P,
  });
  return [
    "scrypt",
    SCRYPT_N,
    SCRYPT_R,
    SCRYPT_P,
    salt.toString("base64url"),
    hash.toString("base64url"),
  ].join(":");
}

/** Replace-or-append our two vars; every other .env.local line is untouched. */
function patchEnvLocal(entries: Record<string, string>): void {
  const envPath = path.join(process.cwd(), ".env.local");
  const existing = existsSync(envPath) ? readFileSync(envPath, "utf8") : "";
  const kept = existing
    .split("\n")
    .filter(
      (line) =>
        !Object.keys(entries).some((name) => line.startsWith(`${name}=`)) &&
        !line.startsWith("# Cross-device sync auth"),
    );
  while (kept.length > 0 && kept[kept.length - 1].trim() === "") kept.pop();
  const lines = [
    ...kept,
    "",
    "# Cross-device sync auth (generated by scripts/sync-setup.ts)",
    ...Object.entries(entries).map(([name, value]) => `${name}=${value}`),
    "",
  ];
  writeFileSync(envPath, lines.join("\n"));
}

function pushVercelEnv(name: string, value: string): boolean {
  const result = spawnSync(
    "vercel",
    ["env", "add", name, "production", "--force"],
    { input: value, stdio: ["pipe", "inherit", "inherit"] },
  );
  return result.status === 0;
}

function main(): void {
  const isDev = process.argv.includes("--dev");
  const pushEnv = process.argv.includes("--push-env");

  const code = isDev ? "dev-code-not-secret" : generateAccessCode();
  const hash = hashAccessCode(code);
  const sessionSecret = randomBytes(32).toString("base64url");

  patchEnvLocal({
    SYNC_ACCESS_CODE_HASH: hash,
    SYNC_SESSION_SECRET: sessionSecret,
  });
  console.log("✓ .env.local updated (hash + session secret; other lines untouched)");

  if (pushEnv) {
    const ok =
      pushVercelEnv("SYNC_ACCESS_CODE_HASH", hash) &&
      pushVercelEnv("SYNC_SESSION_SECRET", sessionSecret);
    console.log(
      ok
        ? "✓ Vercel production env updated — redeploy to apply"
        : "✗ vercel env add failed — run manually:\n" +
            "    vercel env add SYNC_ACCESS_CODE_HASH production --force  (paste the hash from .env.local)\n" +
            "    vercel env add SYNC_SESSION_SECRET production --force   (paste the secret from .env.local)",
    );
  }

  if (isDev) {
    console.log(`\nDev access code (NOT a secret): ${code}`);
  } else {
    console.log(
      "\n────────────────────────────────────────────\n" +
        `  你的登入通行密語（只顯示這一次）：\n\n      ${code}\n\n` +
        "  請存進密碼管理器。每台裝置登入時輸入一次即可（180 天有效）。\n" +
        "  忘記了就重跑本腳本換一組（已同步的資料不受影響）。\n" +
        "────────────────────────────────────────────",
    );
    if (!pushEnv) {
      console.log(
        "\n下一步：npx tsx scripts/sync-setup.ts --push-env 可直接寫入 Vercel（或照上面手動指令），完成後 redeploy。",
      );
    }
  }
}

main();
